# Server Port
server.port=4000

# Jackson Settings
spring.jackson.default-property-inclusion=non_null

# Logging configuration
logging.level.org.springframework.web=INFO
logging.level.com.marketplace=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
